import building2 from "../assets/images/building2.png";
import img10 from "../assets/images/img10.jpg";
import img7 from "../assets/images/img7.jpg";
import img11 from "../assets/images/img11.jpg";
import img12 from "../assets/images/img12.png";
import img13 from "../assets/images/img13.png";
import img9 from "../assets/images/img9.jpg";
import img8 from "../assets/images/img8.png";

const projectCard = [
  {
    img: img10,
    classname: "long",
    title: "Sayba Heritage",
    body: "Bldg No.79, S G Barve Marg, Kurla East Mumbai - 400 024.",
    location: "S.G Barve Marg, Kurla (E)",
    feature: true,
    type: "Residential",
    description:
      "Welcome to a new world of perfect living at Passcode Perfect Choice. It offers 1 & 2 bed luxury apartments with finely crafted rooftop indulgences. Strategically positioned in a thriving locale of Kurla East, it is surrounded by conveniences and provides easy accessibility to all parts of the city. Perfect Choice RERA Number P51800033318",
    year: "Current",
    amenities: [
      "Green Lawn",
      "Meditation Area",
      "Reflexology Path",
      "Viewing Lounge ",
      "Gazebo",
      "Wooden Deck Seating",
    ],
    address: "https://goo.gl/maps/HAeKNK6E7RMvDoFi8",
    iframe:
      "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3771.046083515088!2d72.8821644142125!3d19.061711357376417!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3be7c8bd76bb73ef%3A0xbe05d4d01375bd56!2s79%2C%20SG%20Barve%20Marg%2C%20Police%20Colony%2C%20Kurla%2C%20Mumbai%2C%20Maharashtra%20400024!5e0!3m2!1sen!2sin!4v1658482760110!5m2!1sen!2sin",
  },
  {
    img: img7,
    classname: "long",
    title: "Sayba Delux",
    body: "Star Deluxe, Bldg No.35, Bearing C.T.S No. 11(Pt.) A Nehru Nagar, Kurla(East), Mumbai- 400024",
    location: "A Nehru Nagar, Kurla (E)",
    feature: true,
    type: "Residential",
    description:
      "Star Deluxe is located at a prime area of Nehru Nagar, Kurla East is a successful project by Sayba Group. Raised with 17 Floors, it is built with supreme quality materials by highly experienced team. It is led by Architect Atul Situt & Associates, Consulting Architect K Arch Architects, ECC Consultant N.S. Lele & Associates & Legal Consultants Little & Co. and Ajay Khatlawala Advocates & Solicitors.",
    year: "Current",
    amenities: [
      "Premium Vitrified Flooring",
      "Stainless Steel Sink",
      "Full Height French Windows With 5mm Glass",
      "Additional Dry Platform",
      "Premium Vitrified Flooring",
      "Premium Anti-skid Flooring",
      "Granite platform",
      "Elegant C.P. Fittings & Diverter For Hot & Cold Water",
      "Scratch Resistant",
      "RCC Frame Structure",
      "Attractive Entrance Lobby",
      "Ample Car Parking Space",
      "3 High Speed Elevators",
      "Advance Secure Fire Fighting System",
      "Integrated Security System With 24 Hours Surveillance By CCTV",
      "Durable Weather Proof Exterior Emulsion Paint For Long Lasting Finish",
    ],
    address: "https://goo.gl/maps/Biu12ReSnH3ufvsc6",
    iframe:
      "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3771.0127675382305!2d72.87924241421254!3d19.063176257330817!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3be7c9c43642f5cd%3A0x729d9156c1f33a41!2sStar%20Deluxe!5e0!3m2!1sen!2sin!4v1658482904126!5m2!1sen!2sin",
  },
  {
    img: img11,
    classname: "short",
    title: "Sayba Annex",
    body: "SAYBA-ANNEX, Building No. 32, Nehru Nagar, MHADA Colony, Kurla (E), Mumbai - 400024",
    location: "MHADA Colony, Kurla (E)",
    feature: true,
    type: "Residential",
    description:
      "A home where dreams come true A warm Welcome to Sayba - Annex, a spectacle from the house of Sayba Group. Step into a world, which is a blend of unparalleled level of luxury and pleasurable living, located at Kurla East. A 16 Storied high rise, sprawled across a spacious arena, is your chance to escape to a fine living. The flats are designed to reflect grandeur and high luxurious living. Sayba - Annex has 2 wings of with wide choice of 1 BHK, 2 BHK and 3 BHK Apartments. Your unlaurelled life style now includes a world class amenities and conveniences - to live the fun life and embrace every moment because your every need is satisfied.",
    year: "Current",
    amenities: [
      "Anodized aluminum sliding windows",
      "Glazed Tiles dado up-to the ceiling",
      "Swimming Pool",
      "Granite Kitchen Platform with S.S. Sink",
      "Designer tiles in toilets up to full height",
      "Well equipped kids play area",
      "Glazed Tiles dado up-to the ceiling ",
      "Concealed plumbing with exclusive fittings & fixtures",
      "Jogging Track",
      "Anodized aluminum sliding windows",
      "Concealed copper wiring with adequate electrical points",
      "Sitting area",
    ],
    address: "https://goo.gl/maps/ZB2xkqAqiMEk7UXD8",
    iframe:
      "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3771.0168340889454!2d72.87876641421245!3d19.062997457336362!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3be7c9299322cf07%3A0x2bad40ba9ed9de3b!2sSayba%20Annex!5e0!3m2!1sen!2sin!4v1658482989110!5m2!1sen!2sin",
  },
  {
    img: img12,
    classname: "short",
    title: "Sayba Hans",
    body: "Kurla Part 4, Opp. Phoenix Mall, Next To Naaz Hotel, Kurla West, Mumbai- 400070",
    location: "Kurla Part 4, Kurla (E)",
    feature: true,
    type: "Residential",
    description:
      "Pearl Hans is located a prime location of LBS Marg opp. Phoenix Mall, Kurla West.",
    year: "Current",
    amenities: [
      "Well equipped kids play area",
      "Open deck",
      "Jogging track",
      "Indoor games",
      "Sitting area",
      "Sitting Arrangement",
      "Swimming pool",
      "Gym",
    ],
    address: "",
    iframe: "",
  },
  {
    img: img13,
    classname: "long",
    title: "GAGAN - 139",
    body: "Building No. 139, Nehru Nagar, Off Mother Dairy Road, Kurla East, Mumbai -400024",
    location: "Nehru Nagar, Kurla (E)",
    feature: false,
    type: "Residential",
    description:
      "WELCOME TO GAGAN - 139 A world of luxurious 1, 2 & 3 BHK residences, Gagan-139 offers a lifestyle that's class apart. short it is the perfect place for starting a Journey which offers a peaceful and fruitful life for years to come.",
    year: "Current",
    amenities: [
      "Elegant PGVT Flooring In Entire Carpet Area Of Flat.",
      "Under Ground & Over Head Water Tank.",
      "Acrylic / Plastic paint With Gypsum Finishes.",
      "Rain Water Harvesting.",
      "Solid Flush Door Both Side",
      "Fire Equipments.",
      "C. P. Teakwood Finish For Main Door.",
      "Branded Elevators.",
      "Laminated Flush Doors For Bedrooms & Bathrooms",
      "CCTV Surveillance System",
      "Earthquake Resisant R.C.C. Framed Structure",
      "DG Backup",
      "Tower Parking",
      "Fitness Centre",
      "Pouder Coated / Anodised Aluminum Sliding Windows",
      "Elegant French Windows With Sill",
      "Granite Kitchen Platform With Single Bowl",
      "Stainless Steel Kitchen Sink",
    ],
    address: "https://goo.gl/maps/9rjrXef4Aa1BgtK5A",
    iframe:
      "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3770.990325795003!2d72.88255261421256!3d19.06416295730011!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3be7c9110030c825%3A0x136095939eb27c17!2sGagan!5e0!3m2!1sen!2sin!4v1658483112933!5m2!1sen!2sin",
  },
  {
    img: building2,
    classname: "long",
    title: "Sayba Icon",
    body: "CTS No. 183, Kurla Part 4, Near Taximen Colony, LB.S Marg, Kurla (West), Mumbai - 400070.",
    location: "LB.S Marg, Kurla (W)",
    feature: true,
    type: "Residential",
    description:
      "Sayba Icon is Gen-Next Home. Kurla's Next Residental Icon. Connectivity at it's best : International Airport: 25 Minutes Eastern Express Highway: 20 Minutes Bandra Kurla Complex: 8 Minutes Western Express Highway: 20 Minutes Kurla Railway Station: 6 Minutes Maha RERA No : P51800027784",
    year: "Current",
    amenities: [
      "Infinity jacuzzi",
      "Jogging Track",
      "Gym",
      "Kids Play Area",
      "Yoga Deck",
      "Sitting Arrangements",
    ],
    address: "https://goo.gl/maps/6662ahYomBDSXkn47",
    iframe:
      "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3770.920346757125!2d72.87053291566609!3d19.067239421984986!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3be7c943b07853a5%3A0x67cd99bfad93fce0!2sSayba%20Icon!5e0!3m2!1sen!2sin!4v1658483145398!5m2!1sen!2sin",
  },
  {
    img: img9,
    classname: "short",
    title: "Sayba residency",
    body: "Sayba Residency, 89/90, Village Kurla, Mother Dairy Rd, Nehru Nagar, Kurla, Mumbai, Maharashtra 400024",
    location: "Nehru Nagar, Kurla (E)",
    feature: true,
    type: "Residential",
    description:
      "Sayba Residency is a pride of Sayba Group. A world of luxurious 1, 2 & 3 BHK residences, Sayba Residency offers a lifestyle that's class apart. Laden with best-in-class amenities and superior it's your ideal dwelling abode.",
    year: "Current",
    amenities: [
      "Kids play area",
      "Anodized aluminum sliding windows",
      "Concealed plumbing with exclusive fittings & fixtures",
      "Terrace garden",
      "Granite kitchen platform with S.S. sink",
      "Concealed copper wiring with adequate electrical points",
      "Library room",
      "Glazed tiles dado up to the ceiling",
      "Well equipped kids play area",
      "Indoor games",
      "Designer vitrified flooring",
      "Jogging track",
      "AV room",
      "Designer tiles in toilets up to full height",
      "Sitting area",
    ],
    address: "https://goo.gl/maps/ac8FTaRCMBwoNLsPA",
    iframe:
      "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3771.005562284372!2d72.88291121421253!3d19.063493057320915!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3be7c970f3f169c5%3A0xc2537a1b8fd17fda!2sSayba%20Residency!5e0!3m2!1sen!2sin!4v1658483187510!5m2!1sen!2sin",
  },
  {
    img: img8,
    classname: "short",
    title: "Sayba Emerald",
    body: "SAYBA EMERALD Near Lucky Restaurant, Opposite to Bandra Bus Depot and Hakka mama Restaurant, Bandra West, Mumbai-400050",
    location: "Bandra Bus Depot, Bandra (W)",
    feature: true,
    type: "Residential",
    description:
      "Sayba Group - a construction company that requires no introduction in the construction vertical. With over 18 years of excellence in this segment, we have successfully completed 35 projects. At Sayba we believe in delivering quality and strive to find better solutions for our clients. The priority of Sayba Group has been the timely delivery of projects. The Organization maintains a strong foundation of trust and mutual respect generated through positive relationship with clients, architects, engineers, subcontractors and suppliers.",
    year: "Current",
    amenities: [
      "Italian Flooring for Living and Dining Room",
      "Concealed Copper Wiring MCB and ELCBs in every Flat",
      "Vitrified Flooring for Kitchen",
      "Anodized/ Power Coated Aluminum Sliding windows",
      "Italian Flooring for Bedrooms",
      "Decorative Main & Internal Doors with Good Ouality Hardware Fitting",
      "Walls & Ceiling Painted with Superior Quality Paint",
      "Designer Ceramic Tiles on Walls upto Door Heights",
      "Ample Electrical Points with Modular Switches",
      "Telephone & Cable T.V. Points in Living and Bedrooms",
      "Well Designed bathrooms with Anti Skid Flooring",
      "Concealed Plumbing Systems",
      "Hot & Cold Water Diverter",
      "Provision for Exhaust Fan and Geyser",
      "Good Sanitary Ware Bathroom Fittings",
    ],
    address: "",
    iframe: "",
  },
];

export default projectCard;
